# @folio = http://localhost:5000
@folio = https://folio-staging.openup.org.za
# @keycloak = http://keycloak.local
# @keycloak = https://keycloak-staging.openup.org.za
@keycloak = http://localhost:8080

# @song = http://song.local
@song = https://song-staging.openup.org.za


# @minio = http://minio.local
@minio = http://localhost:9000

@realm = agari
@client_id = dms
@client_secret = VDyLEjGR3xDQvoQlrHq5AB6OwbW0Refc

@username = system.admin@agari.tech
# @username = owner@org1.ac.za
# @username = owner@org2.ac.za
# @username = org-admin@org1.ac.za
# @username = org-admin@org2.ac.za
# @username = test-user1@example.com
# @username = test-user2@example.com
# @username = test-user3@example.com


@password = pass123

@testuser1 = a056925c-4d53-417f-a9f6-45e4421654cc

### 1. LOGIN to get access token
# @name login
POST {{keycloak}}/realms/{{realm}}/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

username={{username}}
&password={{password}}
&grant_type=password
&client_id={{client_id}}
&client_secret={{client_secret}}

###
@token = {{login.response.body.access_token}}

### Keycloak generate magic link
@redirect_uri = https://agari.openup.org.za
# @name magiclink
POST {{keycloak}}/realms/{{realm}}/magic-link
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "email": "michael@openup.org.za",
  "client_id": "dms",
  "redirect_uri": "https://agari.openup.org.za",
  "expiration_seconds": 3600,
  "send_email": false
}

### Keycloak authenticate with code
POST {{keycloak}}/realms/agari/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id={{client_id}}
&client_secret={{client_secret}}
&grant_type=authorization_code
&code=[add code here]
&redirect_uri={{redirect_uri}}

##########################
### INFO
##########################

# @name health
GET {{folio}}/info/health

###

# @name databaseHealth
GET {{folio}}/info//health/db

###

# @name whoami
GET {{folio}}/info/whoami
Authorization: Bearer {{token}}

###

# @name permissions
GET {{folio}}/info/permissions
Authorization: Bearer {{token}}

###

# @name userHasResourcePermission

POST {{folio}}/info/permissions/check
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "permission": "create_project",
    "resource_type": "project",
    "resource_id": "80bd4fd2-10e3-4104-abe2-713dfdd92bfa"
}


###

# @name permission_check
POST {{folio}}/info/permissions/check
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "permission": "view_org_private_projects",
    "resource_type": "project",
    "resource_id": "80bd4fd2-10e3-4104-abe2-713dfdd92bfa"
}

##########################
### USERS
##########################

# @name get_current_user
GET {{folio}}/info/whoami
Authorization: Bearer {{token}}

###

# @name get_user_by_id
GET {{folio}}/users/{{testuser1}}
Authorization: Bearer {{token}}

###

# @name update_user_by_id
PUT {{folio}}/users/{{testuser1}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "name",
  "surname" : "surname",
  "email": "testuser1@example.com",
  "bio": "lorem",
  "preferences": {
    "theme": "dark"
  },
  "accepted_terms": true,
  "accepted_governance": true
}

##########################
## ORGANISATIONS
##########################


# @name list_organisations
GET {{folio}}/organisations
Authorization: Bearer {{token}}

###

# @name create_organisation
POST {{folio}}/organisations/
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name": "The National Institute For Communicable Diseases",
    "abbreviation": "NICD",
    "about": "About NICD",
    "url": "https://www.nicd.ac.za"
}

###

@organisation_id = 783b767c-c41e-4a6a-9132-ea52fadb8e17

# @name get_organisation
GET {{folio}}/organisations/{{organisation_id}}
Authorization: Bearer {{token}}

###

# @name update_organisation
PUT {{folio}}/organisations/{{organisation_id}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "about": "Updated Organisation 3"
}

###

# @name delete_organisation
DELETE {{folio}}/organisations/{{organisation_id}}
Authorization: Bearer {{token}}

###

# @name add_organisation_member
POST {{folio}}/organisations/{{organisation_id}}/members
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "user_id": "3948dda5-f903-44eb-8d16-759fed3492a1",
    "role": "org-owner"
}

###

# @name organisation_users
GET {{folio}}/organisations/{{organisation_id}}/members
Authorization: Bearer {{token}}



##########################
### PATHOGENS
##########################

# @name list_pathogens
GET {{folio}}/pathogens

###

# @name list_pathogens_deleted
GET {{folio}}/pathogens?deleted=true

###

# @name create_pathogen
POST {{folio}}/pathogens
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name": "Cholera",
    "description": "Cholera Virus",
    "scientific_name": "Vibrio cholerae"
}

###

@pathogen_id = 6d2494af-a5e5-4965-8494-ad618ba844db

# @name get_pathogen
GET {{folio}}/pathogens/{{pathogen_id}}

###

# @name delete_pathogen
DELETE {{folio}}/pathogens/{{pathogen_id}}
Authorization: Bearer {{token}}

###

# @name delete_pathogen_hard
DELETE {{folio}}/pathogens/{{pathogen_id}}?hard=true
Authorization: Bearer {{token}}

###

# @update_pathogen
PUT {{folio}}/pathogens/{{pathogen_id}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name": "Cholera",
    "description": "Cholera virus",
    "scientific_name": "Vibrio cholerae"
}

###

# @name restore_pathogen
POST {{folio}}/pathogens/{{pathogen_id}}/restore
Authorization: Bearer {{token}}


###

# @name register_schema
POST {{song}}/schemas
Authorization: Bearer {{token}}
Content-Type: application/json

< ./cholera_schema.json


###

# @name list_schemas
GET {{song}}/schemas
Authorization: Bearer {{token}}


###


##########################
### PROJECTS
##########################

# @name list_projects
GET {{folio}}/projects

Authorization: Bearer {{token}}

###

# @name create_project
POST {{folio}}/projects
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name": "Cholera Project2",
    "description": "Project description2",
    "pathogen_id": "{{pathogen_id}}",
    "privacy": "public"
}

###

@project_id = 2bc307f3-22a7-4b61-b97d-cfff86d61b31

### @name get_project
GET {{folio}}/projects/{{project_id}}
Authorization: Bearer {{token}}

###

# @name update_project
PUT {{folio}}/projects/{{project_id}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "privacy": "public"
}

###

# @name delete_project
DELETE {{folio}}/projects/{{project_id}}
Authorization: Bearer {{token}}

###

# @name delete_project_hard
DELETE {{folio}}/projects/{{project_id}}?hard=true
Authorization: Bearer {{token}}

###

# @name restore_project
POST {{folio}}/projects/{{project_id}}/restore
Authorization: Bearer {{token}}

##########################
### PROJECT USERS
##########################

# @name list_project_users
GET {{folio}}/projects/{{project_id}}/users
Authorization: Bearer {{token}}

###

# @name add_project_users
POST {{folio}}/projects/{{project_id}}/users
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "user_id": "282dd9ee-ad7e-4580-9677-fa37d7ba6435",
    "role": "project-contributor"
}

###

@user_id = 638e2410-c4cf-4854-8258-d600ac289bcc

# @name delete_project_users
DELETE {{folio}}/projects/{{project_id}}/users/{{user_id}}
Authorization: Bearer {{token}}


##########################
### STUDIES
##########################

# @name list_studies
GET {{folio}}/studies
Authorization: Bearer {{token}}

###

@study_id = cholera-999
@study_folio_id = 73feb9b9-915b-41c2-bb4a-908ed10668e8

# @name create_study
POST {{folio}}/studies/
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "studyId": "{{study_id}}",
    "name": "AGARI Test Study", 
    "description": "Test study for genomic data workflow",
    "projectId": "{{project_id}}",
    "info": {
        "projectType": "genomics",
        "region": "South Africa"
    }
}

##########################
### SONG
##########################

# @name get_studies_in_song
GET {{song}}/studies/all
Authorization: Bearer {{token}}


###

# @name get_study_in_song
GET {{song}}/studies/{{study_id}}
Authorization: Bearer {{token}}

###


##########################
### SUBMISSIONS
##########################

# @name getProjectSubmissions
GET {{folio}}/projects/{{project_id}}/submissions
Authorization: Bearer {{token}}

###


# @name submitAnalysisFile
POST {{folio}}/projects/{{project_id}}/submissions
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary123

------WebKitFormBoundary123
Content-Disposition: form-data; name="metadata"

{
  "studyId": "{{study_id}}",
  "analysisType": {
    "name": "cholera_schema",
    "version": 4
  },
  "submissionName": "Cholera TSV Submission",
  "files": [
    {
      "fileName": "cholera2.fasta",
      "fileType": "FASTA",
      "fileSize": 6643,
      "fileMd5sum": "1dfd8800948e9f2bf44942003f9265fm",
      "fileAccess": "open",
      "dataType": "Cholera Genome"
    }
  ]
}

------WebKitFormBoundary123
Content-Disposition: form-data; name="file"; filename="multiple-cholera.tsv"
Content-Type: text/plain

< /home/dimee/Work/OpenUp/SANBI/agari-folio/test/multiple-cholera.tsv

------WebKitFormBoundary123--

###

@submission_id = 8c296739-c9a4-40cb-88dd-8df6e7d79a64

# @name getSubmissionDetails
GET {{folio}}/projects/{{project_id}}/submissions/{{submission_id}}
Authorization: Bearer {{token}}

###

@object_id = 0ebc4e28-b0c7-590b-bc36-f4344d983329

# @name upload_init
POST {{folio}}/projects/{{project_id}}/submissions/{{submission_id}}/upload/init
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "object_id": "{{object_id}}",
    "overwrite": true,
    "fileSize": 6643,
    "md5": "1dfd8800948e9f2bf44942003f9265fm"
}

###

# @name upload_file_to_minio

@url = https://minio-staging.openup.org.za/object/data/0ebc4e28-b0c7-590b-bc36-f4344d983329?uploadId=Mjc1Njc3MDktNmZiNS00MTczLWEwOTEtOGQ5Njg4Y2YzZDg5LjNlNDBiMjcxLTA1MGMtNDQ3ZC1iNjU5LTZkZTdkYmU3YjgzNQ&partNumber=1&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20251029T185530Z&X-Amz-SignedHeaders=host&X-Amz-Expires=518399&X-Amz-Credential=admin%2F20251029%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Signature=f44afe7395cc8b7fa0411e6e12e0a19b7269a90aaf64c3157bb9d075d971cdbc
PUT {{url}}
Content-Type: application/octet-stream

< /home/dimee/Work/OpenUp/SANBI/agari-folio/test/cholera2.fasta


###


# @name finalise_part
POST {{folio}}/projects/{{project_id}}/submissions/{{submission_id}}/upload/finalise-part
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "object_id": "{{object_id}}",
  "upload_id": "Mjc1Njc3MDktNmZiNS00MTczLWEwOTEtOGQ5Njg4Y2YzZDg5LjNlNDBiMjcxLTA1MGMtNDQ3ZC1iNjU5LTZkZTdkYmU3YjgzNQ",
  "etag": "bda8ea08a3e76e699a0248038737649d",
  "part_number": 1,
  "md5": "1dfd8800948e9f2bf44942003f9265fm"
}

###

# @name finalize_upload
POST {{folio}}/projects/{{project_id}}/submissions/{{submission_id}}/upload/finalise
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "object_id": "7ecdaca1-897d-59c2-ab54-8ff17ab2c0ad",
  "upload_id": "Mjc1Njc3MDktNmZiNS00MTczLWEwOTEtOGQ5Njg4Y2YzZDg5LjhhMjJhZWM4LWExOGItNGI5ZC1hZjRkLTZmYWFjZTNhZjBjNw",
  "parts": [
    {
      "part_number": 1,
      "etag": "bda8ea08a3e76e699a0248038737649d"
    }
  ]
}



###

# @name publish_analysis
POST {{folio}}/projects/{{project_id}}/submissions/{{submission_id}}/publish
Authorization: Bearer {{token}}



##########################
### SONG
##########################


@analysis_id = e7c07e97-5ded-43ed-807e-975dedf3ed54


# @name list_study_analyses
GET http://song.local/studies/{{study_id}}/analysis?analysisStates=PUBLISHED,UNPUBLISHED
Authorization: Bearer {{token}}

###

# @name get_study_analyses
GET http://song.local/{{study_id}}/analysis/{{analysis_id}}
Authorization: Bearer {{token}}

###

### Get user by email
# @name getUserByEmail
GET {{keycloak}}/admin/realms/{{realm}}/users?email=michael@openup.org.za
Authorization: Bearer {{token}}

###
@user_id = 9af85893-2402-4069-95ef-16045ab5a77f

### Keycloak update user details
PUT {{keycloak}}/admin/realms/{{realm}}/users/{{user_id}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "firstName": "Michael"
}

### Create new user in Keycloak
# @name createUser
POST {{keycloak}}/admin/realms/{{realm}}/users
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "username": "newuser@example.com",
  "email": "newuser@example.com",
  "enabled": false,
  "attributes": {
    "invite": ["sent"]
  }
}

### Create new user in Folio magic link
# @name createUserMagicLink
POST {{folio}}/users/
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "email": "michael@openup.org.za",
  "redirect_uri": "https://agari.openup.org.za/",
  "send_email": "false"
}


##########################
### OLD
##########################


# @name upload_analysis_file_rest
POST {{folio}}/studies/{{study_id}}/analysis/{{analysis_id}}/upload
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary123

------WebKitFormBoundary123
Content-Disposition: form-data; name="object_id"

{{object_id_from_analysis}}
------WebKitFormBoundary123
Content-Disposition: form-data; name="overwrite"

true
------WebKitFormBoundary123
Content-Disposition: form-data; name="file"; filename="test_data.fasta"
Content-Type: text/plain

< /media/dimee/Work/OpenUp/SANBI/agari-folio/test/LS997867.1 Vibrio cholerae strain NCTC 30 genome assembly, chromosome 1.fasta

------WebKitFormBoundary123--
