@folio = http://localhost:5000


@realm = agari
@client_id = dms
@client_secret = VDyLEjGR3xDQvoQlrHq5AB6OwbW0Refc

# @username = system.admin@agari.tech
@username = owner@org1.ac.za
# @username = owner@org2.ac.za
# @username = org-admin@org1.ac.za
# @username = org-admin@org2.ac.za
# @username = test-user1@example.com
# @username = test-user2@example.com
# @username = test-user3@example.com


@password = pass123

### 1. LOGIN to get access token
# @name login
POST http://keycloak.local/realms/{{realm}}/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

username={{username}}
&password={{password}}
&grant_type=password
&client_id={{client_id}}
&client_secret={{client_secret}}

###
@token = {{login.response.body.access_token}}

### Keycloak generate magic link
@redirect_uri = https://agari.openup.org.za
# @name magiclink
POST https://keycloak-ilifu.openup.org.za/realms/{{realm}}/magic-link
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "email": "michael@openup.org.za",
  "client_id": "dms",
  "redirect_uri": "https://agari.openup.org.za",
  "expiration_seconds": 3600,
  "send_email": false
}

### Keycloak authenticate with code
POST https://keycloak-ilifu.openup.org.za/realms/agari/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id={{client_id}}
&client_secret={{client_secret}}
&grant_type=authorization_code
&code=[add code here]
&redirect_uri={{redirect_uri}}

##########################
### INFO
##########################

# @name health
GET {{folio}}/info/health

###

# @name databaseHealth
GET {{folio}}/info//health/db

###

# @name whoami
GET {{folio}}/info/whoami
Authorization: Bearer {{token}}

###

# @name permissions
GET {{folio}}/info/permissions
Authorization: Bearer {{token}}

###

# @name userHasResourcePermission

POST {{folio}}/info/permissions/check
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "permission": "create_project",
    "resource_type": "project",
    "resource_id": "80bd4fd2-10e3-4104-abe2-713dfdd92bfa"
}


###

# @name permission_check
POST {{folio}}/info/permissions/check
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "permission": "view_org_private_projects",
    "resource_type": "project",
    "resource_id": "80bd4fd2-10e3-4104-abe2-713dfdd92bfa"
}

##########################
### PATHOGENS
##########################

# @name list_pathogens
GET {{folio}}/pathogens

###

# @name list_pathogens_deleted
GET {{folio}}/pathogens?deleted=true

###

# @name create_pathogen
POST {{folio}}/pathogens
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name": "Cholera4",
    "description": "Cholera Virus4",
    "scientific_name": "Vibrio cholerae4"
}

###

@pathogen_id = 0683f0f6-04b3-4005-a078-383d0e3e88f2

# @name get_pathogen
GET {{folio}}/pathogens/{{pathogen_id}}

###

# @name delete_pathogen
DELETE {{folio}}/pathogens/{{pathogen_id}}
Authorization: Bearer {{token}}

###

# @name delete_pathogen_hard
DELETE {{folio}}/pathogens/{{pathogen_id}}?hard=true
Authorization: Bearer {{token}}

###

# @update_pathogen
PUT {{folio}}/pathogens/{{pathogen_id}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name": "Cholera",
    "description": "Cholera virus",
    "scientific_name": "Vibrio cholerae"
}

###

# @name restore_pathogen
POST {{folio}}/pathogens/{{pathogen_id}}/restore
Authorization: Bearer {{token}}

##########################
### PROJECTS
##########################

# @name list_projects
GET {{folio}}/projects
Authorization: Bearer {{token}}

###

# @name create_project
POST {{folio}}/projects
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name": "Cholera Project2",
    "description": "Project description2",
    "pathogen_id": "{{pathogen_id}}",
    "privacy": "public"
}

###

@project_id = 8772fbeb-5c94-41d6-8159-48290874378b

### @name get_project
GET {{folio}}/projects/{{project_id}}
Authorization: Bearer {{token}}

###

# @name update_project
PUT {{folio}}/projects/{{project_id}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "privacy": "private"
}

###

# @name delete_project
DELETE {{folio}}/projects/{{project_id}}
Authorization: Bearer {{token}}

###

# @name delete_project_hard
DELETE {{folio}}/projects/{{project_id}}?hard=true
Authorization: Bearer {{token}}

###

# @name restore_project
POST {{folio}}/projects/{{project_id}}/restore
Authorization: Bearer {{token}}

##########################
### PROJECT USERS
##########################

# @name list_project_users
GET {{folio}}/projects/{{project_id}}/users
Authorization: Bearer {{token}}

###

# @name add_project_users
POST {{folio}}/projects/{{project_id}}/users
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "user_id": "282dd9ee-ad7e-4580-9677-fa37d7ba6435",
    "role": "project-contributor"
}

###

@user_id = 638e2410-c4cf-4854-8258-d600ac289bcc

# @name delete_project_users
DELETE {{folio}}/projects/{{project_id}}/users/{{user_id}}
Authorization: Bearer {{token}}


##########################
### STUDIES
##########################

# @name list_studies
GET {{folio}}/studies
Authorization: Bearer {{token}}

###

@study_id = study-003

# @name create_study
POST {{folio}}/studies/
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "studyId": "{{study_id}}",
    "name": "AGARI Test Study", 
    "description": "Test study for genomic data workflow",
    "projectId": "{{project_id}}",
    "info": {
        "projectType": "genomics",
        "region": "South Africa"
    }
}

### 

# @name get_studies_in_song
GET http://song.local/studies/all
Authorization: Bearer {{token}}


###

# @name get_study_in_song
GET http://song.local/studies/{{study_id}}
Authorization: Bearer {{token}}

###

# @name submitAnalysis
POST {{folio}}/studies/submit/{{study_id}}/
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "studyId": "study-003",
  "analysisId": "analysis001",
  "analysisType": {
    "name": "sequencingRead",
    "version": 1
  },
  "samples": [
    {
      "sampleId": "SA001",
      "submitterSampleId": "SA001",
      "sampleType": "Total DNA",
      "matchedNormalSubmitterSampleId": null,
      "specimen": {
        "specimenId": "SP001", 
        "submitterSpecimenId": "SP001",
        "specimenType": "Normal",
        "specimenTissueSource": "Blood derived",
        "tumourNormalDesignation": "Normal"
      },
      "donor": {
        "studyId": "study-003",
        "donorId": "D001",
        "submitterDonorId": "D001",
        "gender": "Female"
      }
    }
  ],
  "files": [
    {
      "fileName": "test_data.fasta",
      "fileType": "FASTA",
      "fileSize": 298,
      "fileMd5sum": "cc70b8e811b39c98a938edf87145e34d",
      "fileAccess": "open",
      "dataType": "Sequencing Reads"
    }
  ],
  "experiment": {
    "libraryStrategy": "WGS",
    "pairedEnd": false,
    "aligned": false
  }
}

###

@analysis_id = f1646e21-6c01-4f09-a46e-216c01af09d6

# @name list_study_analyses
GET http://song.local/studies/{{study_id}}/analysis?analysisStates=PUBLISHED,UNPUBLISHED
Authorization: Bearer {{token}}

###

# @name get_study_analyses
GET http://song.local/{{study_id}}/analysis/{{analysis_id}}
Authorization: Bearer {{token}}

###

# @name upload_analysis_file_curl
curl -X POST http://song.local/studies/study-002/analysis/f1646e21-6c01-4f09-a46e-216c01af09d6/upload -H "Authorization: Bearer {{token}}" -F "object_id=14e5f58a-73ed-5359-8101-e3ae6d544fbc" -F "overwrite=true" -F "file=@/home/dimee/Work/OpenUp/SANBI/agari-folio/test/test_data.fasta"

###

@object_id_from_analysis = 2966b6aa-7570-53a5-9392-740bd61221d5

# @name upload_analysis_file_rest
POST {{folio}}/studies/{{study_id}}/analysis/{{analysis_id}}/upload
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary123

------WebKitFormBoundary123
Content-Disposition: form-data; name="object_id"

{{object_id_from_analysis}}
------WebKitFormBoundary123
Content-Disposition: form-data; name="overwrite"

true
------WebKitFormBoundary123
Content-Disposition: form-data; name="file"; filename="test_data.fasta"
Content-Type: text/plain

< /media/michael/Data4/sanbi/agari-folio/test/test_data.fasta

------WebKitFormBoundary123--
###

# @name publish_analysis
POST {{folio}}/studies/{{study_id}}/analysis/publish/{{analysis_id}}
Authorization: Bearer {{token}}

### Get user by email
# @name getUserByEmail
GET https://keycloak-ilifu.openup.org.za/admin/realms/{{realm}}/users?email=michael@openup.org.za
Authorization: Bearer {{token}}

###
@user_id = 9af85893-2402-4069-95ef-16045ab5a77f

### Keycloak update user details
PUT https://keycloak-ilifu.openup.org.za/admin/realms/{{realm}}/users/{{user_id}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "firstName": "Michael"
}

### Create new user in Keycloak
# @name createUser
POST https://keycloak-ilifu.openup.org.za/admin/realms/{{realm}}/users
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "username": "newuser@example.com",
  "email": "newuser@example.com",
  "enabled": false,
  "attributes": {
    "invite": ["sent"]
  }
}