services:
  folio-db:
    image: postgres:14
    environment:
      POSTGRES_DB: folio
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: folio-db-pass-123
    ports:
      - "5434:5432"
    volumes:
      - folio-db-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d folio"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Keycloak Database
  keycloak-db:
    image: postgres:14
    container_name: keycloak-db
    environment:
      POSTGRES_DB: keycloak_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: keycloak-db-pass-123
    ports:
      - "5433:5432"
    volumes:
      - keycloak-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d keycloak_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Keycloak
  keycloak:
    image: quay.io/phasetwo/phasetwo-keycloak:26.2.5
    container_name: keycloak
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/keycloak_db
      KC_DB_USERNAME: admin
      KC_DB_PASSWORD: keycloak-db-pass-123
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin123
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME_STRICT_HTTPS: "false"
      KC_PROXY: edge
      KC_FEATURES: preview
      KC_CORS_ORIGINS: "*"
      JAVA_OPTS_APPEND: "-Djava.awt.headless=true -Djboss.modules.system.pkgs=org.jboss.byteman -Djava.net.preferIPv4Stack=true -server -Xms512m -Xmx768m"
    command:
      - start-dev
      # "If a realm already exists in the server, the import operation is skipped."
      - --import-realm
    volumes:
      - ./test/agari-realm-rbac.json:/opt/keycloak/data/import/agari-realm-rbac.json:ro
    ports:
      - "8080:8080"
    depends_on:
      keycloak-db:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "exec 3<>/dev/tcp/127.0.0.1/8080;echo -e 'GET /health/ready HTTP/1.1\r\nhost: 127.0.0.1:8080\r\nConnection: close\r\n\r\n' >&3;if [ $? -eq 0 ]; then exit 0;else exit 1;fi;exec 3<&-;exec 3>&-"]
      interval: 30s
      timeout: 15s
      retries: 12
      start_period: 120s

volumes:
  keycloak-db-data:
  folio-db-data:
